spring:
  application:
    name: securitycheck
  datasource:
    url: jdbc:hsqldb:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always


service-maintenance:
  base-url: "http://service-maintenance.webfleet"

web:
  message: Welcome to WeB Fleet Security

---
spring:
  config:
    activate:
      on-profile: "local"
service-maintenance:
  base-url: "http://localhost:8081"
