spring:
  application:
    name: tanzu-java-web-app
  datasource: 
    url: jdbc:mysql://mysql/webfleet
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
