spring:
  application:
    name: tanzu-java-web-app
  datasource:
    url: jdbc:hsqldb:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always

web:
  message: Welcome to WeB Fleet Security
