spring:
  application:
    name: tanzu-java-web-app
  datasource: 
    url: jdbc:mysql://mysql/webfleet
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
database: mysql
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
