spring:
  application:
    name: securitycheck
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

service-maintenance:
  base-url: "http://service-maintenance.webfleet"

web:
  message: Welcome to WeB Fleet Security V3

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:hsqldb:mem:testdb

service-maintenance:
  base-url: "http://localhost:8081"

