apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: securitycheck
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: securitycheck
    apps.tanzu.vmware.com/has-tests: true
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/bkieling/securitycheck
      ref:
        branch: main
