apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: securitycheck
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: securitycheck
    apps.tanzu.vmware.com/has-tests: true
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: mysql
    ref:
      apiVersion: with.sql.tanzu.vmware.com/v1
      kind: MySQL
      name: mysql
  source:
    git:
      url: https://github.com/sample-accelerators/securitycheck
      ref:
        branch: main
