apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: securitycheck
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: securitycheck
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/test-label: foo
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: mysql
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: mysql
    - name: rmq
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: rmq-1
  source:
    git:
      url: https://github.com/bkieling/securitycheck
      ref:
        branch: main
